services:
  db:
    image: postgres:16
    container_name: kopibudget-postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: kopibudget
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d kopibudget"]
      interval: 30s
      timeout: 10s
      retries: 3

  kopibudget.api:
    build:
      context: .
      dockerfile: ./KopiBudget.Api/Dockerfile
    container_name: kopibudget-api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=kopibudget;Username=dev;Password=dev
    ports:
      - "5000:8080"
      - "5001:8081"

  kopibudget.ui:
    build:
      context: ./KopiBudget.Ui
      dockerfile: Dockerfile
    container_name: kopibudget-ui
    ports:
      - "4200:80"

volumes:
  db_data:
