[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
name = "KopiBudget"
startCommand = "dotnet KopiBudget.Api.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
Jwt__Key = "apPWYbSDFU84HjehZogH/ZCXbFDmhL2g68iv8Guyicv8vJgiAipYuX7Mw3a0KSX60gSRxjlnMyAmNs9F/TpGrQ=="
