[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
name = "KopiBudget"
startCommand = "dotnet KopiBudget.Api.dll"

[deploy]
postDeployCommand = "dotnet ef database update --project KopiBudget.Infrastructure/KopiBudget.Infrastructure.csproj --startup-project KopiBudget.Api/KopiBudget.Api.csproj"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ConnectionStrings__DefaultConnection = "Host=db.hjsepjjcvdiypqjieseh.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=Mn#m0n1c5123;Include Error Detail=true"
Jwt__Key = "apPWYbSDFU84HjehZogH/ZCXbFDmhL2g68iv8Guyicv8vJgiAipYuX7Mw3a0KSX60gSRxjlnMyAmNs9F/TpGrQ=="
