[build]
baseImage = "ubuntu-22.04"

[phases]
setup = [
    "curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0",
    "export DOTNET_ROOT=$HOME/.dotnet",
    "export PATH=$PATH:$HOME/.dotnet"
]

[install]
cmds = ["dotnet restore"]

[build]
cmds = ["dotnet publish -c Release -o /app/output"]

[start]
cmd = "dotnet /app/output/KopiBudget.Api.dll"