name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd KopiBudget.Ui
          npm install

      - name: Build Angular app
        run: |
          cd KopiBudget.Ui
          npm run build -- --configuration=github

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Pull latest images
            docker pull codecoffee2024/kopibudget-ui:latest
            docker pull codecoffee2024/kopibudget-api:latest

            # Deploy with compose
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d

            # Clean up
            docker system prune -f
