name: .NET API CI/CD (Railway)

on:
  push:
    paths:
      - 'KopiBudget.Api/**'
      - '.github/workflows/server-ci.yml'
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore Dependencies
        working-directory: ./KopiBudget.Api/KopiBudget.Api
        run: dotnet restore

      - name: Build
        working-directory: ./KopiBudget.Api/KopiBudget.Api
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ./KopiBudget.Api/KopiBudget.Api
        run: dotnet test --configuration Release --no-build --verbosity normal

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    # Only deploy when pushing to main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service=KopiBudget
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
