name: .NET API CI/CD (Railway)

on:
  push:
    paths:
      - 'KopiBudget.Api/**'
      - '.github/workflows/server-ci.yml'
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        working-directory: ./KopiBudget.Api
        run: dotnet restore KopiBudget.Api.csproj

      - name: Build
        working-directory: ./KopiBudget.Api
        run: dotnet build KopiBudget.Api.csproj --configuration Release --no-restore


  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        working-directory: ./KopiBudget.Api
        run: railway up --service=KopiBudget
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
